### ISSUE TITLE
Pick a DID Method for the Credential Issuer

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/interop-project#2]
Anything supported by https://uniresolver.io/ seems like a good candidate.

Keep in mind that the issuer just needs to have a DID with a key that is available to the credential issuing server. Its a one time setup to get the key into the DID Document, so cost for ledger methods should be safe to ignore.

Add your method or vote for one.

**Comment by OR13** [comment]
`elem`

I'm biased obviously and its still under pretty active development, but `elem` does not have restrictions on keys, so anything `jose` compatible is fine, as well as the custom signature formats used by uport / jolocom over secp256k1.

Also its not added to the universal resolver yet.

**Comment by OR13** [comment]
`ethr`

We added support for larger key sizes so RSA is a possibility, so is ethereum address linked credentials.

**Comment by OR13** [comment]
`github`

I'm biased here as well, but it might be cool to show that centralized DID Methods 👿 can be used to issuer credentials for other DIDs.

Github DID uses a github repository so it has a nature linkage to real world human or organization IDs, and it has built in tools for creating your ID for free, and creating and verifying JSON-LD based credentials.

**Comment by OR13** [comment]
I suppose we can support multiple issuer DIDs if they are all resolvable via the universal resolver, and all their keys are available to the issuer server.

Its a bit extra work, but it might be nice to show that:

example.com can issue credentials from:

`ethr`,`btcr`, `sov`, etc... to `ethr`, `btcr`, `sov`, `jolo`, etc...

**Comment by OR13** [comment]
We are adopting BTC-R for the issuer DID, assuming we do not have a problem registering keys.

**Comment by nembal** [comment]
> We are adopting BTC-R for the issuer DID, assuming we do not have a problem registering keys.

@OR13 - This might be a worthwhile topic to drop for the upcoming BTC-R hackathon.

**Comment by OR13** [comment]
@nembal would you mind linking any details of the hackathon here / reach out to the organizers?

**Comment by nembal** [comment]
@OR13 https://weboftrustinfo.github.io/btcr-hackathon-2019/
Kim H. is the organizer (or as far as I know) and she is back from holidays only on the 4th Aug. Scheduled a message to her.
